<?php
/**
 * ProjectsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ProjectsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation projectsList
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PaginatedProjectList
     */
    public function projectsList($xAccountToken, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $remoteId = null)
    {
        list($response) = $this->projectsListWithHttpInfo($xAccountToken, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $remoteId);
        return $response;
    }

    /**
     * Operation projectsListWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PaginatedProjectList, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectsListWithHttpInfo($xAccountToken, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $remoteId = null)
    {
        $request = $this->projectsListRequest($xAccountToken, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $remoteId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\PaginatedProjectList' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PaginatedProjectList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PaginatedProjectList';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PaginatedProjectList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectsListAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectsListAsync($xAccountToken, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $remoteId = null)
    {
        return $this->projectsListAsyncWithHttpInfo($xAccountToken, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $remoteId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectsListAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectsListAsyncWithHttpInfo($xAccountToken, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $remoteId = null)
    {
        $returnType = '\OpenAPI\Client\Model\PaginatedProjectList';
        $request = $this->projectsListRequest($xAccountToken, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $remoteId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectsList'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectsListRequest($xAccountToken, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $remoteId = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling projectsList'
            );
        }

        $resourcePath = '/projects';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($createdAfter !== null) {
            if('form' === 'form' && is_array($createdAfter)) {
                foreach($createdAfter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_after'] = $createdAfter;
            }
        }
        // query params
        if ($createdBefore !== null) {
            if('form' === 'form' && is_array($createdBefore)) {
                foreach($createdBefore as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_before'] = $createdBefore;
            }
        }
        // query params
        if ($cursor !== null) {
            if('form' === 'form' && is_array($cursor)) {
                foreach($cursor as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['cursor'] = $cursor;
            }
        }
        // query params
        if ($includeDeletedData !== null) {
            if('form' === 'form' && is_array($includeDeletedData)) {
                foreach($includeDeletedData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_deleted_data'] = $includeDeletedData;
            }
        }
        // query params
        if ($includeRemoteData !== null) {
            if('form' === 'form' && is_array($includeRemoteData)) {
                foreach($includeRemoteData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $includeRemoteData;
            }
        }
        // query params
        if ($modifiedAfter !== null) {
            if('form' === 'form' && is_array($modifiedAfter)) {
                foreach($modifiedAfter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modified_after'] = $modifiedAfter;
            }
        }
        // query params
        if ($modifiedBefore !== null) {
            if('form' === 'form' && is_array($modifiedBefore)) {
                foreach($modifiedBefore as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modified_before'] = $modifiedBefore;
            }
        }
        // query params
        if ($pageSize !== null) {
            if('form' === 'form' && is_array($pageSize)) {
                foreach($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page_size'] = $pageSize;
            }
        }
        // query params
        if ($remoteId !== null) {
            if('form' === 'form' && is_array($remoteId)) {
                foreach($remoteId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['remote_id'] = $remoteId;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectsRetrieve
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Project
     */
    public function projectsRetrieve($xAccountToken, $id, $includeRemoteData = null)
    {
        list($response) = $this->projectsRetrieveWithHttpInfo($xAccountToken, $id, $includeRemoteData);
        return $response;
    }

    /**
     * Operation projectsRetrieveWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Project, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectsRetrieveWithHttpInfo($xAccountToken, $id, $includeRemoteData = null)
    {
        $request = $this->projectsRetrieveRequest($xAccountToken, $id, $includeRemoteData);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Project' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Project', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Project';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Project',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectsRetrieveAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectsRetrieveAsync($xAccountToken, $id, $includeRemoteData = null)
    {
        return $this->projectsRetrieveAsyncWithHttpInfo($xAccountToken, $id, $includeRemoteData)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectsRetrieveAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectsRetrieveAsyncWithHttpInfo($xAccountToken, $id, $includeRemoteData = null)
    {
        $returnType = '\OpenAPI\Client\Model\Project';
        $request = $this->projectsRetrieveRequest($xAccountToken, $id, $includeRemoteData);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectsRetrieve'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectsRetrieveRequest($xAccountToken, $id, $includeRemoteData = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling projectsRetrieve'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling projectsRetrieve'
            );
        }

        $resourcePath = '/projects/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($includeRemoteData !== null) {
            if('form' === 'form' && is_array($includeRemoteData)) {
                foreach($includeRemoteData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $includeRemoteData;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectsUsersList
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PaginatedUserList
     */
    public function projectsUsersList($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        list($response) = $this->projectsUsersListWithHttpInfo($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize);
        return $response;
    }

    /**
     * Operation projectsUsersListWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PaginatedUserList, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectsUsersListWithHttpInfo($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        $request = $this->projectsUsersListRequest($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\PaginatedUserList' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PaginatedUserList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PaginatedUserList';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PaginatedUserList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectsUsersListAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectsUsersListAsync($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        return $this->projectsUsersListAsyncWithHttpInfo($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectsUsersListAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectsUsersListAsyncWithHttpInfo($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        $returnType = '\OpenAPI\Client\Model\PaginatedUserList';
        $request = $this->projectsUsersListRequest($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectsUsersList'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectsUsersListRequest($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling projectsUsersList'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling projectsUsersList'
            );
        }

        $resourcePath = '/projects/{id}/users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($cursor !== null) {
            if('form' === 'form' && is_array($cursor)) {
                foreach($cursor as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['cursor'] = $cursor;
            }
        }
        // query params
        if ($includeRemoteData !== null) {
            if('form' === 'form' && is_array($includeRemoteData)) {
                foreach($includeRemoteData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $includeRemoteData;
            }
        }
        // query params
        if ($pageSize !== null) {
            if('form' === 'form' && is_array($pageSize)) {
                foreach($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page_size'] = $pageSize;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
