<?php
/**
 * TicketsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * TicketsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TicketsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation ticketsCollaboratorsList
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PaginatedUserList
     */
    public function ticketsCollaboratorsList($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        list($response) = $this->ticketsCollaboratorsListWithHttpInfo($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize);
        return $response;
    }

    /**
     * Operation ticketsCollaboratorsListWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PaginatedUserList, HTTP status code, HTTP response headers (array of strings)
     */
    public function ticketsCollaboratorsListWithHttpInfo($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        $request = $this->ticketsCollaboratorsListRequest($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\PaginatedUserList' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PaginatedUserList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PaginatedUserList';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PaginatedUserList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ticketsCollaboratorsListAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsCollaboratorsListAsync($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        return $this->ticketsCollaboratorsListAsyncWithHttpInfo($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ticketsCollaboratorsListAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsCollaboratorsListAsyncWithHttpInfo($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        $returnType = '\OpenAPI\Client\Model\PaginatedUserList';
        $request = $this->ticketsCollaboratorsListRequest($xAccountToken, $id, $cursor, $includeRemoteData, $pageSize);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ticketsCollaboratorsList'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ticketsCollaboratorsListRequest($xAccountToken, $id, $cursor = null, $includeRemoteData = null, $pageSize = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling ticketsCollaboratorsList'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling ticketsCollaboratorsList'
            );
        }

        $resourcePath = '/tickets/{id}/collaborators';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($cursor !== null) {
            if('form' === 'form' && is_array($cursor)) {
                foreach($cursor as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['cursor'] = $cursor;
            }
        }
        // query params
        if ($includeRemoteData !== null) {
            if('form' === 'form' && is_array($includeRemoteData)) {
                foreach($includeRemoteData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $includeRemoteData;
            }
        }
        // query params
        if ($pageSize !== null) {
            if('form' === 'form' && is_array($pageSize)) {
                foreach($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page_size'] = $pageSize;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ticketsCreate
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \OpenAPI\Client\Model\TicketEndpointRequest $ticketEndpointRequest ticketEndpointRequest (required)
     * @param  bool $isDebugMode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $runAsync Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TicketResponse
     */
    public function ticketsCreate($xAccountToken, $ticketEndpointRequest, $isDebugMode = null, $runAsync = null)
    {
        list($response) = $this->ticketsCreateWithHttpInfo($xAccountToken, $ticketEndpointRequest, $isDebugMode, $runAsync);
        return $response;
    }

    /**
     * Operation ticketsCreateWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \OpenAPI\Client\Model\TicketEndpointRequest $ticketEndpointRequest (required)
     * @param  bool $isDebugMode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $runAsync Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TicketResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function ticketsCreateWithHttpInfo($xAccountToken, $ticketEndpointRequest, $isDebugMode = null, $runAsync = null)
    {
        $request = $this->ticketsCreateRequest($xAccountToken, $ticketEndpointRequest, $isDebugMode, $runAsync);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Model\TicketResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\TicketResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\TicketResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TicketResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ticketsCreateAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \OpenAPI\Client\Model\TicketEndpointRequest $ticketEndpointRequest (required)
     * @param  bool $isDebugMode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $runAsync Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsCreateAsync($xAccountToken, $ticketEndpointRequest, $isDebugMode = null, $runAsync = null)
    {
        return $this->ticketsCreateAsyncWithHttpInfo($xAccountToken, $ticketEndpointRequest, $isDebugMode, $runAsync)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ticketsCreateAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \OpenAPI\Client\Model\TicketEndpointRequest $ticketEndpointRequest (required)
     * @param  bool $isDebugMode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $runAsync Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsCreateAsyncWithHttpInfo($xAccountToken, $ticketEndpointRequest, $isDebugMode = null, $runAsync = null)
    {
        $returnType = '\OpenAPI\Client\Model\TicketResponse';
        $request = $this->ticketsCreateRequest($xAccountToken, $ticketEndpointRequest, $isDebugMode, $runAsync);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ticketsCreate'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  \OpenAPI\Client\Model\TicketEndpointRequest $ticketEndpointRequest (required)
     * @param  bool $isDebugMode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $runAsync Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ticketsCreateRequest($xAccountToken, $ticketEndpointRequest, $isDebugMode = null, $runAsync = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling ticketsCreate'
            );
        }
        // verify the required parameter 'ticketEndpointRequest' is set
        if ($ticketEndpointRequest === null || (is_array($ticketEndpointRequest) && count($ticketEndpointRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ticketEndpointRequest when calling ticketsCreate'
            );
        }

        $resourcePath = '/tickets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($isDebugMode !== null) {
            if('form' === 'form' && is_array($isDebugMode)) {
                foreach($isDebugMode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['is_debug_mode'] = $isDebugMode;
            }
        }
        // query params
        if ($runAsync !== null) {
            if('form' === 'form' && is_array($runAsync)) {
                foreach($runAsync as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['run_async'] = $runAsync;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($ticketEndpointRequest)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($ticketEndpointRequest));
            } else {
                $httpBody = $ticketEndpointRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ticketsList
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $accountId If provided, will only return tickets for this account. (optional)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $projectId If provided, will only return tickets for this project. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PaginatedTicketList
     */
    public function ticketsList($xAccountToken, $accountId = null, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $projectId = null, $remoteFields = null, $remoteId = null)
    {
        list($response) = $this->ticketsListWithHttpInfo($xAccountToken, $accountId, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $projectId, $remoteFields, $remoteId);
        return $response;
    }

    /**
     * Operation ticketsListWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $accountId If provided, will only return tickets for this account. (optional)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $projectId If provided, will only return tickets for this project. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PaginatedTicketList, HTTP status code, HTTP response headers (array of strings)
     */
    public function ticketsListWithHttpInfo($xAccountToken, $accountId = null, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $projectId = null, $remoteFields = null, $remoteId = null)
    {
        $request = $this->ticketsListRequest($xAccountToken, $accountId, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $projectId, $remoteFields, $remoteId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\PaginatedTicketList' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PaginatedTicketList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PaginatedTicketList';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PaginatedTicketList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ticketsListAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $accountId If provided, will only return tickets for this account. (optional)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $projectId If provided, will only return tickets for this project. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsListAsync($xAccountToken, $accountId = null, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $projectId = null, $remoteFields = null, $remoteId = null)
    {
        return $this->ticketsListAsyncWithHttpInfo($xAccountToken, $accountId, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $projectId, $remoteFields, $remoteId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ticketsListAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $accountId If provided, will only return tickets for this account. (optional)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $projectId If provided, will only return tickets for this project. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsListAsyncWithHttpInfo($xAccountToken, $accountId = null, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $projectId = null, $remoteFields = null, $remoteId = null)
    {
        $returnType = '\OpenAPI\Client\Model\PaginatedTicketList';
        $request = $this->ticketsListRequest($xAccountToken, $accountId, $createdAfter, $createdBefore, $cursor, $includeDeletedData, $includeRemoteData, $modifiedAfter, $modifiedBefore, $pageSize, $projectId, $remoteFields, $remoteId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ticketsList'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $accountId If provided, will only return tickets for this account. (optional)
     * @param  \DateTime $createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  \DateTime $modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param  int $pageSize Number of results to return per page. (optional)
     * @param  string $projectId If provided, will only return tickets for this project. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     * @param  string $remoteId The API provider&#39;s ID for the given object. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ticketsListRequest($xAccountToken, $accountId = null, $createdAfter = null, $createdBefore = null, $cursor = null, $includeDeletedData = null, $includeRemoteData = null, $modifiedAfter = null, $modifiedBefore = null, $pageSize = null, $projectId = null, $remoteFields = null, $remoteId = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling ticketsList'
            );
        }

        $resourcePath = '/tickets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($accountId !== null) {
            if('form' === 'form' && is_array($accountId)) {
                foreach($accountId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['account_id'] = $accountId;
            }
        }
        // query params
        if ($createdAfter !== null) {
            if('form' === 'form' && is_array($createdAfter)) {
                foreach($createdAfter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_after'] = $createdAfter;
            }
        }
        // query params
        if ($createdBefore !== null) {
            if('form' === 'form' && is_array($createdBefore)) {
                foreach($createdBefore as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_before'] = $createdBefore;
            }
        }
        // query params
        if ($cursor !== null) {
            if('form' === 'form' && is_array($cursor)) {
                foreach($cursor as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['cursor'] = $cursor;
            }
        }
        // query params
        if ($includeDeletedData !== null) {
            if('form' === 'form' && is_array($includeDeletedData)) {
                foreach($includeDeletedData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_deleted_data'] = $includeDeletedData;
            }
        }
        // query params
        if ($includeRemoteData !== null) {
            if('form' === 'form' && is_array($includeRemoteData)) {
                foreach($includeRemoteData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $includeRemoteData;
            }
        }
        // query params
        if ($modifiedAfter !== null) {
            if('form' === 'form' && is_array($modifiedAfter)) {
                foreach($modifiedAfter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modified_after'] = $modifiedAfter;
            }
        }
        // query params
        if ($modifiedBefore !== null) {
            if('form' === 'form' && is_array($modifiedBefore)) {
                foreach($modifiedBefore as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modified_before'] = $modifiedBefore;
            }
        }
        // query params
        if ($pageSize !== null) {
            if('form' === 'form' && is_array($pageSize)) {
                foreach($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page_size'] = $pageSize;
            }
        }
        // query params
        if ($projectId !== null) {
            if('form' === 'form' && is_array($projectId)) {
                foreach($projectId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['project_id'] = $projectId;
            }
        }
        // query params
        if ($remoteFields !== null) {
            if('form' === 'form' && is_array($remoteFields)) {
                foreach($remoteFields as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['remote_fields'] = $remoteFields;
            }
        }
        // query params
        if ($remoteId !== null) {
            if('form' === 'form' && is_array($remoteId)) {
                foreach($remoteId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['remote_id'] = $remoteId;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ticketsMetaPostRetrieve
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MetaResponse
     */
    public function ticketsMetaPostRetrieve($xAccountToken)
    {
        list($response) = $this->ticketsMetaPostRetrieveWithHttpInfo($xAccountToken);
        return $response;
    }

    /**
     * Operation ticketsMetaPostRetrieveWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MetaResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function ticketsMetaPostRetrieveWithHttpInfo($xAccountToken)
    {
        $request = $this->ticketsMetaPostRetrieveRequest($xAccountToken);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\MetaResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\MetaResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\MetaResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MetaResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ticketsMetaPostRetrieveAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsMetaPostRetrieveAsync($xAccountToken)
    {
        return $this->ticketsMetaPostRetrieveAsyncWithHttpInfo($xAccountToken)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ticketsMetaPostRetrieveAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsMetaPostRetrieveAsyncWithHttpInfo($xAccountToken)
    {
        $returnType = '\OpenAPI\Client\Model\MetaResponse';
        $request = $this->ticketsMetaPostRetrieveRequest($xAccountToken);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ticketsMetaPostRetrieve'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ticketsMetaPostRetrieveRequest($xAccountToken)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling ticketsMetaPostRetrieve'
            );
        }

        $resourcePath = '/tickets/meta/post';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ticketsRetrieve
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Ticket
     */
    public function ticketsRetrieve($xAccountToken, $id, $includeRemoteData = null, $remoteFields = null)
    {
        list($response) = $this->ticketsRetrieveWithHttpInfo($xAccountToken, $id, $includeRemoteData, $remoteFields);
        return $response;
    }

    /**
     * Operation ticketsRetrieveWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Ticket, HTTP status code, HTTP response headers (array of strings)
     */
    public function ticketsRetrieveWithHttpInfo($xAccountToken, $id, $includeRemoteData = null, $remoteFields = null)
    {
        $request = $this->ticketsRetrieveRequest($xAccountToken, $id, $includeRemoteData, $remoteFields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Ticket' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Ticket', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Ticket';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Ticket',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ticketsRetrieveAsync
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsRetrieveAsync($xAccountToken, $id, $includeRemoteData = null, $remoteFields = null)
    {
        return $this->ticketsRetrieveAsyncWithHttpInfo($xAccountToken, $id, $includeRemoteData, $remoteFields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ticketsRetrieveAsyncWithHttpInfo
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ticketsRetrieveAsyncWithHttpInfo($xAccountToken, $id, $includeRemoteData = null, $remoteFields = null)
    {
        $returnType = '\OpenAPI\Client\Model\Ticket';
        $request = $this->ticketsRetrieveRequest($xAccountToken, $id, $includeRemoteData, $remoteFields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ticketsRetrieve'
     *
     * @param  string $xAccountToken Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $remoteFields Which fields should be returned in non-normalized form. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ticketsRetrieveRequest($xAccountToken, $id, $includeRemoteData = null, $remoteFields = null)
    {
        // verify the required parameter 'xAccountToken' is set
        if ($xAccountToken === null || (is_array($xAccountToken) && count($xAccountToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $xAccountToken when calling ticketsRetrieve'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling ticketsRetrieve'
            );
        }

        $resourcePath = '/tickets/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($includeRemoteData !== null) {
            if('form' === 'form' && is_array($includeRemoteData)) {
                foreach($includeRemoteData as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $includeRemoteData;
            }
        }
        // query params
        if ($remoteFields !== null) {
            if('form' === 'form' && is_array($remoteFields)) {
                foreach($remoteFields as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['remote_fields'] = $remoteFields;
            }
        }

        // header params
        if ($xAccountToken !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($xAccountToken);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
