<?php
/**
 * AccountDetailsAndActions
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AccountDetailsAndActions Class Doc Comment
 *
 * @category Class
 * @description # The LinkedAccount Object ### Description The &#x60;LinkedAccount&#x60; object is used to represent an end user&#39;s link with a specific integration.  ### Usage Example View a list of your organization&#39;s &#x60;LinkedAccount&#x60; objects.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AccountDetailsAndActions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountDetailsAndActions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'category' => 'CategoryEnum',
        'status' => 'AccountDetailsAndActionsStatusEnum',
        'statusDetail' => 'string',
        'endUserOriginId' => 'string',
        'endUserOrganizationName' => 'string',
        'endUserEmailAddress' => 'string',
        'webhookListenerUrl' => 'string',
        'integration' => '\OpenAPI\Client\Model\AccountDetailsAndActionsIntegration'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'category' => null,
        'status' => null,
        'statusDetail' => null,
        'endUserOriginId' => null,
        'endUserOrganizationName' => null,
        'endUserEmailAddress' => null,
        'webhookListenerUrl' => null,
        'integration' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'category' => 'category',
        'status' => 'status',
        'statusDetail' => 'status_detail',
        'endUserOriginId' => 'end_user_origin_id',
        'endUserOrganizationName' => 'end_user_organization_name',
        'endUserEmailAddress' => 'end_user_email_address',
        'webhookListenerUrl' => 'webhook_listener_url',
        'integration' => 'integration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'category' => 'setCategory',
        'status' => 'setStatus',
        'statusDetail' => 'setStatusDetail',
        'endUserOriginId' => 'setEndUserOriginId',
        'endUserOrganizationName' => 'setEndUserOrganizationName',
        'endUserEmailAddress' => 'setEndUserEmailAddress',
        'webhookListenerUrl' => 'setWebhookListenerUrl',
        'integration' => 'setIntegration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'category' => 'getCategory',
        'status' => 'getStatus',
        'statusDetail' => 'getStatusDetail',
        'endUserOriginId' => 'getEndUserOriginId',
        'endUserOrganizationName' => 'getEndUserOrganizationName',
        'endUserEmailAddress' => 'getEndUserEmailAddress',
        'webhookListenerUrl' => 'getWebhookListenerUrl',
        'integration' => 'getIntegration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['category'] = $data['category'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['statusDetail'] = $data['statusDetail'] ?? null;
        $this->container['endUserOriginId'] = $data['endUserOriginId'] ?? null;
        $this->container['endUserOrganizationName'] = $data['endUserOrganizationName'] ?? null;
        $this->container['endUserEmailAddress'] = $data['endUserEmailAddress'] ?? null;
        $this->container['webhookListenerUrl'] = $data['webhookListenerUrl'] ?? null;
        $this->container['integration'] = $data['integration'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['endUserOrganizationName'] === null) {
            $invalidProperties[] = "'endUserOrganizationName' can't be null";
        }
        if ($this->container['endUserEmailAddress'] === null) {
            $invalidProperties[] = "'endUserEmailAddress' can't be null";
        }
        if ($this->container['webhookListenerUrl'] === null) {
            $invalidProperties[] = "'webhookListenerUrl' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets category
     *
     * @return CategoryEnum|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param CategoryEnum|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets status
     *
     * @return AccountDetailsAndActionsStatusEnum
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param AccountDetailsAndActionsStatusEnum $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets statusDetail
     *
     * @return string|null
     */
    public function getStatusDetail()
    {
        return $this->container['statusDetail'];
    }

    /**
     * Sets statusDetail
     *
     * @param string|null $statusDetail statusDetail
     *
     * @return self
     */
    public function setStatusDetail($statusDetail)
    {
        $this->container['statusDetail'] = $statusDetail;

        return $this;
    }

    /**
     * Gets endUserOriginId
     *
     * @return string|null
     */
    public function getEndUserOriginId()
    {
        return $this->container['endUserOriginId'];
    }

    /**
     * Sets endUserOriginId
     *
     * @param string|null $endUserOriginId endUserOriginId
     *
     * @return self
     */
    public function setEndUserOriginId($endUserOriginId)
    {
        $this->container['endUserOriginId'] = $endUserOriginId;

        return $this;
    }

    /**
     * Gets endUserOrganizationName
     *
     * @return string
     */
    public function getEndUserOrganizationName()
    {
        return $this->container['endUserOrganizationName'];
    }

    /**
     * Sets endUserOrganizationName
     *
     * @param string $endUserOrganizationName endUserOrganizationName
     *
     * @return self
     */
    public function setEndUserOrganizationName($endUserOrganizationName)
    {
        $this->container['endUserOrganizationName'] = $endUserOrganizationName;

        return $this;
    }

    /**
     * Gets endUserEmailAddress
     *
     * @return string
     */
    public function getEndUserEmailAddress()
    {
        return $this->container['endUserEmailAddress'];
    }

    /**
     * Sets endUserEmailAddress
     *
     * @param string $endUserEmailAddress endUserEmailAddress
     *
     * @return self
     */
    public function setEndUserEmailAddress($endUserEmailAddress)
    {
        $this->container['endUserEmailAddress'] = $endUserEmailAddress;

        return $this;
    }

    /**
     * Gets webhookListenerUrl
     *
     * @return string
     */
    public function getWebhookListenerUrl()
    {
        return $this->container['webhookListenerUrl'];
    }

    /**
     * Sets webhookListenerUrl
     *
     * @param string $webhookListenerUrl webhookListenerUrl
     *
     * @return self
     */
    public function setWebhookListenerUrl($webhookListenerUrl)
    {
        $this->container['webhookListenerUrl'] = $webhookListenerUrl;

        return $this;
    }

    /**
     * Gets integration
     *
     * @return \OpenAPI\Client\Model\AccountDetailsAndActionsIntegration|null
     */
    public function getIntegration()
    {
        return $this->container['integration'];
    }

    /**
     * Sets integration
     *
     * @param \OpenAPI\Client\Model\AccountDetailsAndActionsIntegration|null $integration integration
     *
     * @return self
     */
    public function setIntegration($integration)
    {
        $this->container['integration'] = $integration;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


