<?php
/**
 * AttachmentRequest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AttachmentRequest Class Doc Comment
 *
 * @category Class
 * @description # The Attachment Object ### Description The &#x60;Attachment&#x60; object is used to represent an attachment for a ticket.  ### Usage Example TODO
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AttachmentRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AttachmentRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'remoteId' => 'string',
        'fileName' => 'string',
        'ticket' => 'string',
        'fileUrl' => 'string',
        'contentType' => 'string',
        'uploadedBy' => 'string',
        'remoteCreatedAt' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'remoteId' => null,
        'fileName' => null,
        'ticket' => 'uuid',
        'fileUrl' => null,
        'contentType' => null,
        'uploadedBy' => 'uuid',
        'remoteCreatedAt' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'remoteId' => 'remote_id',
        'fileName' => 'file_name',
        'ticket' => 'ticket',
        'fileUrl' => 'file_url',
        'contentType' => 'content_type',
        'uploadedBy' => 'uploaded_by',
        'remoteCreatedAt' => 'remote_created_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'remoteId' => 'setRemoteId',
        'fileName' => 'setFileName',
        'ticket' => 'setTicket',
        'fileUrl' => 'setFileUrl',
        'contentType' => 'setContentType',
        'uploadedBy' => 'setUploadedBy',
        'remoteCreatedAt' => 'setRemoteCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'remoteId' => 'getRemoteId',
        'fileName' => 'getFileName',
        'ticket' => 'getTicket',
        'fileUrl' => 'getFileUrl',
        'contentType' => 'getContentType',
        'uploadedBy' => 'getUploadedBy',
        'remoteCreatedAt' => 'getRemoteCreatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['remoteId'] = $data['remoteId'] ?? null;
        $this->container['fileName'] = $data['fileName'] ?? null;
        $this->container['ticket'] = $data['ticket'] ?? null;
        $this->container['fileUrl'] = $data['fileUrl'] ?? null;
        $this->container['contentType'] = $data['contentType'] ?? null;
        $this->container['uploadedBy'] = $data['uploadedBy'] ?? null;
        $this->container['remoteCreatedAt'] = $data['remoteCreatedAt'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets remoteId
     *
     * @return string|null
     */
    public function getRemoteId()
    {
        return $this->container['remoteId'];
    }

    /**
     * Sets remoteId
     *
     * @param string|null $remoteId The third-party API ID of the matching object.
     *
     * @return self
     */
    public function setRemoteId($remoteId)
    {
        $this->container['remoteId'] = $remoteId;

        return $this;
    }

    /**
     * Gets fileName
     *
     * @return string|null
     */
    public function getFileName()
    {
        return $this->container['fileName'];
    }

    /**
     * Sets fileName
     *
     * @param string|null $fileName The attachment's name.
     *
     * @return self
     */
    public function setFileName($fileName)
    {
        $this->container['fileName'] = $fileName;

        return $this;
    }

    /**
     * Gets ticket
     *
     * @return string|null
     */
    public function getTicket()
    {
        return $this->container['ticket'];
    }

    /**
     * Sets ticket
     *
     * @param string|null $ticket ticket
     *
     * @return self
     */
    public function setTicket($ticket)
    {
        $this->container['ticket'] = $ticket;

        return $this;
    }

    /**
     * Gets fileUrl
     *
     * @return string|null
     */
    public function getFileUrl()
    {
        return $this->container['fileUrl'];
    }

    /**
     * Sets fileUrl
     *
     * @param string|null $fileUrl The attachment's url.
     *
     * @return self
     */
    public function setFileUrl($fileUrl)
    {
        $this->container['fileUrl'] = $fileUrl;

        return $this;
    }

    /**
     * Gets contentType
     *
     * @return string|null
     */
    public function getContentType()
    {
        return $this->container['contentType'];
    }

    /**
     * Sets contentType
     *
     * @param string|null $contentType The attachment's file format.
     *
     * @return self
     */
    public function setContentType($contentType)
    {
        $this->container['contentType'] = $contentType;

        return $this;
    }

    /**
     * Gets uploadedBy
     *
     * @return string|null
     */
    public function getUploadedBy()
    {
        return $this->container['uploadedBy'];
    }

    /**
     * Sets uploadedBy
     *
     * @param string|null $uploadedBy uploadedBy
     *
     * @return self
     */
    public function setUploadedBy($uploadedBy)
    {
        $this->container['uploadedBy'] = $uploadedBy;

        return $this;
    }

    /**
     * Gets remoteCreatedAt
     *
     * @return \DateTime|null
     */
    public function getRemoteCreatedAt()
    {
        return $this->container['remoteCreatedAt'];
    }

    /**
     * Sets remoteCreatedAt
     *
     * @param \DateTime|null $remoteCreatedAt When the third party's attachment was created.
     *
     * @return self
     */
    public function setRemoteCreatedAt($remoteCreatedAt)
    {
        $this->container['remoteCreatedAt'] = $remoteCreatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


