<?php
/**
 * Comment
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Comment Class Doc Comment
 *
 * @category Class
 * @description # The Comment Object ### Description The &#x60;Comment&#x60; object is used to represent a comment on a ticket.  ### Usage Example TODO
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Comment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Comment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'remoteId' => 'string',
        'user' => 'string',
        'contact' => 'string',
        'body' => 'string',
        'htmlBody' => 'string',
        'ticket' => 'string',
        'isPrivate' => 'bool',
        'remoteCreatedAt' => '\DateTime',
        'remoteData' => '\OpenAPI\Client\Model\RemoteData[]',
        'remoteWasDeleted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'remoteId' => null,
        'user' => 'uuid',
        'contact' => 'uuid',
        'body' => null,
        'htmlBody' => null,
        'ticket' => 'uuid',
        'isPrivate' => null,
        'remoteCreatedAt' => 'date-time',
        'remoteData' => null,
        'remoteWasDeleted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'remoteId' => 'remote_id',
        'user' => 'user',
        'contact' => 'contact',
        'body' => 'body',
        'htmlBody' => 'html_body',
        'ticket' => 'ticket',
        'isPrivate' => 'is_private',
        'remoteCreatedAt' => 'remote_created_at',
        'remoteData' => 'remote_data',
        'remoteWasDeleted' => 'remote_was_deleted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'remoteId' => 'setRemoteId',
        'user' => 'setUser',
        'contact' => 'setContact',
        'body' => 'setBody',
        'htmlBody' => 'setHtmlBody',
        'ticket' => 'setTicket',
        'isPrivate' => 'setIsPrivate',
        'remoteCreatedAt' => 'setRemoteCreatedAt',
        'remoteData' => 'setRemoteData',
        'remoteWasDeleted' => 'setRemoteWasDeleted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'remoteId' => 'getRemoteId',
        'user' => 'getUser',
        'contact' => 'getContact',
        'body' => 'getBody',
        'htmlBody' => 'getHtmlBody',
        'ticket' => 'getTicket',
        'isPrivate' => 'getIsPrivate',
        'remoteCreatedAt' => 'getRemoteCreatedAt',
        'remoteData' => 'getRemoteData',
        'remoteWasDeleted' => 'getRemoteWasDeleted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['remoteId'] = $data['remoteId'] ?? null;
        $this->container['user'] = $data['user'] ?? null;
        $this->container['contact'] = $data['contact'] ?? null;
        $this->container['body'] = $data['body'] ?? null;
        $this->container['htmlBody'] = $data['htmlBody'] ?? null;
        $this->container['ticket'] = $data['ticket'] ?? null;
        $this->container['isPrivate'] = $data['isPrivate'] ?? null;
        $this->container['remoteCreatedAt'] = $data['remoteCreatedAt'] ?? null;
        $this->container['remoteData'] = $data['remoteData'] ?? null;
        $this->container['remoteWasDeleted'] = $data['remoteWasDeleted'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets remoteId
     *
     * @return string|null
     */
    public function getRemoteId()
    {
        return $this->container['remoteId'];
    }

    /**
     * Sets remoteId
     *
     * @param string|null $remoteId The third-party API ID of the matching object.
     *
     * @return self
     */
    public function setRemoteId($remoteId)
    {
        $this->container['remoteId'] = $remoteId;

        return $this;
    }

    /**
     * Gets user
     *
     * @return string|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param string|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return string|null
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param string|null $contact contact
     *
     * @return self
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string|null
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string|null $body The comment's text body.
     *
     * @return self
     */
    public function setBody($body)
    {
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets htmlBody
     *
     * @return string|null
     */
    public function getHtmlBody()
    {
        return $this->container['htmlBody'];
    }

    /**
     * Sets htmlBody
     *
     * @param string|null $htmlBody The comment's text body formatted as html.
     *
     * @return self
     */
    public function setHtmlBody($htmlBody)
    {
        $this->container['htmlBody'] = $htmlBody;

        return $this;
    }

    /**
     * Gets ticket
     *
     * @return string|null
     */
    public function getTicket()
    {
        return $this->container['ticket'];
    }

    /**
     * Sets ticket
     *
     * @param string|null $ticket ticket
     *
     * @return self
     */
    public function setTicket($ticket)
    {
        $this->container['ticket'] = $ticket;

        return $this;
    }

    /**
     * Gets isPrivate
     *
     * @return bool|null
     */
    public function getIsPrivate()
    {
        return $this->container['isPrivate'];
    }

    /**
     * Sets isPrivate
     *
     * @param bool|null $isPrivate Whether or not the comment is internal.
     *
     * @return self
     */
    public function setIsPrivate($isPrivate)
    {
        $this->container['isPrivate'] = $isPrivate;

        return $this;
    }

    /**
     * Gets remoteCreatedAt
     *
     * @return \DateTime|null
     */
    public function getRemoteCreatedAt()
    {
        return $this->container['remoteCreatedAt'];
    }

    /**
     * Sets remoteCreatedAt
     *
     * @param \DateTime|null $remoteCreatedAt When the third party's comment was created.
     *
     * @return self
     */
    public function setRemoteCreatedAt($remoteCreatedAt)
    {
        $this->container['remoteCreatedAt'] = $remoteCreatedAt;

        return $this;
    }

    /**
     * Gets remoteData
     *
     * @return \OpenAPI\Client\Model\RemoteData[]|null
     */
    public function getRemoteData()
    {
        return $this->container['remoteData'];
    }

    /**
     * Sets remoteData
     *
     * @param \OpenAPI\Client\Model\RemoteData[]|null $remoteData remoteData
     *
     * @return self
     */
    public function setRemoteData($remoteData)
    {
        $this->container['remoteData'] = $remoteData;

        return $this;
    }

    /**
     * Gets remoteWasDeleted
     *
     * @return bool|null
     */
    public function getRemoteWasDeleted()
    {
        return $this->container['remoteWasDeleted'];
    }

    /**
     * Sets remoteWasDeleted
     *
     * @param bool|null $remoteWasDeleted remoteWasDeleted
     *
     * @return self
     */
    public function setRemoteWasDeleted($remoteWasDeleted)
    {
        $this->container['remoteWasDeleted'] = $remoteWasDeleted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


