<?php
/**
 * ModelOperation
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ModelOperation Class Doc Comment
 *
 * @category Class
 * @description # The ModelOperation Object ### Description The &#x60;ModelOperation&#x60; object is used to represent the operations that are currently supported for a given model.  ### Usage Example View what operations are supported for the &#x60;Candidate&#x60; endpoint.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ModelOperation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ModelOperation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'modelName' => 'string',
        'availableOperations' => 'string[]',
        'requiredPostParameters' => 'string[]',
        'supportedFields' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'modelName' => null,
        'availableOperations' => null,
        'requiredPostParameters' => null,
        'supportedFields' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'modelName' => 'model_name',
        'availableOperations' => 'available_operations',
        'requiredPostParameters' => 'required_post_parameters',
        'supportedFields' => 'supported_fields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'modelName' => 'setModelName',
        'availableOperations' => 'setAvailableOperations',
        'requiredPostParameters' => 'setRequiredPostParameters',
        'supportedFields' => 'setSupportedFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'modelName' => 'getModelName',
        'availableOperations' => 'getAvailableOperations',
        'requiredPostParameters' => 'getRequiredPostParameters',
        'supportedFields' => 'getSupportedFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['modelName'] = $data['modelName'] ?? null;
        $this->container['availableOperations'] = $data['availableOperations'] ?? null;
        $this->container['requiredPostParameters'] = $data['requiredPostParameters'] ?? null;
        $this->container['supportedFields'] = $data['supportedFields'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['modelName'] === null) {
            $invalidProperties[] = "'modelName' can't be null";
        }
        if ($this->container['availableOperations'] === null) {
            $invalidProperties[] = "'availableOperations' can't be null";
        }
        if ($this->container['requiredPostParameters'] === null) {
            $invalidProperties[] = "'requiredPostParameters' can't be null";
        }
        if ($this->container['supportedFields'] === null) {
            $invalidProperties[] = "'supportedFields' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets modelName
     *
     * @return string
     */
    public function getModelName()
    {
        return $this->container['modelName'];
    }

    /**
     * Sets modelName
     *
     * @param string $modelName modelName
     *
     * @return self
     */
    public function setModelName($modelName)
    {
        $this->container['modelName'] = $modelName;

        return $this;
    }

    /**
     * Gets availableOperations
     *
     * @return string[]
     */
    public function getAvailableOperations()
    {
        return $this->container['availableOperations'];
    }

    /**
     * Sets availableOperations
     *
     * @param string[] $availableOperations availableOperations
     *
     * @return self
     */
    public function setAvailableOperations($availableOperations)
    {
        $this->container['availableOperations'] = $availableOperations;

        return $this;
    }

    /**
     * Gets requiredPostParameters
     *
     * @return string[]
     */
    public function getRequiredPostParameters()
    {
        return $this->container['requiredPostParameters'];
    }

    /**
     * Sets requiredPostParameters
     *
     * @param string[] $requiredPostParameters requiredPostParameters
     *
     * @return self
     */
    public function setRequiredPostParameters($requiredPostParameters)
    {
        $this->container['requiredPostParameters'] = $requiredPostParameters;

        return $this;
    }

    /**
     * Gets supportedFields
     *
     * @return string[]
     */
    public function getSupportedFields()
    {
        return $this->container['supportedFields'];
    }

    /**
     * Sets supportedFields
     *
     * @param string[] $supportedFields supportedFields
     *
     * @return self
     */
    public function setSupportedFields($supportedFields)
    {
        $this->container['supportedFields'] = $supportedFields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


