<?php
/**
 * Ticket
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Ticket Class Doc Comment
 *
 * @category Class
 * @description # The Ticket Object ### Description The &#x60;Ticket&#x60; object is used to represent a ticket or a task within a system.  ### Usage Example TODO
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Ticket implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Ticket';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'remoteId' => 'string',
        'name' => 'string',
        'assignees' => 'string[]',
        'dueDate' => '\DateTime',
        'status' => 'TicketStatusEnum',
        'description' => 'string',
        'project' => 'string',
        'ticketType' => 'string',
        'account' => 'string',
        'contact' => 'string',
        'parentTicket' => 'string',
        'attachments' => 'string[]',
        'tags' => 'string[]',
        'remoteCreatedAt' => '\DateTime',
        'remoteUpdatedAt' => '\DateTime',
        'remoteData' => '\OpenAPI\Client\Model\RemoteData[]',
        'remoteWasDeleted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'remoteId' => null,
        'name' => null,
        'assignees' => 'uuid',
        'dueDate' => 'date-time',
        'status' => null,
        'description' => null,
        'project' => 'uuid',
        'ticketType' => null,
        'account' => 'uuid',
        'contact' => 'uuid',
        'parentTicket' => 'uuid',
        'attachments' => 'uuid',
        'tags' => null,
        'remoteCreatedAt' => 'date-time',
        'remoteUpdatedAt' => 'date-time',
        'remoteData' => null,
        'remoteWasDeleted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'remoteId' => 'remote_id',
        'name' => 'name',
        'assignees' => 'assignees',
        'dueDate' => 'due_date',
        'status' => 'status',
        'description' => 'description',
        'project' => 'project',
        'ticketType' => 'ticket_type',
        'account' => 'account',
        'contact' => 'contact',
        'parentTicket' => 'parent_ticket',
        'attachments' => 'attachments',
        'tags' => 'tags',
        'remoteCreatedAt' => 'remote_created_at',
        'remoteUpdatedAt' => 'remote_updated_at',
        'remoteData' => 'remote_data',
        'remoteWasDeleted' => 'remote_was_deleted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'remoteId' => 'setRemoteId',
        'name' => 'setName',
        'assignees' => 'setAssignees',
        'dueDate' => 'setDueDate',
        'status' => 'setStatus',
        'description' => 'setDescription',
        'project' => 'setProject',
        'ticketType' => 'setTicketType',
        'account' => 'setAccount',
        'contact' => 'setContact',
        'parentTicket' => 'setParentTicket',
        'attachments' => 'setAttachments',
        'tags' => 'setTags',
        'remoteCreatedAt' => 'setRemoteCreatedAt',
        'remoteUpdatedAt' => 'setRemoteUpdatedAt',
        'remoteData' => 'setRemoteData',
        'remoteWasDeleted' => 'setRemoteWasDeleted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'remoteId' => 'getRemoteId',
        'name' => 'getName',
        'assignees' => 'getAssignees',
        'dueDate' => 'getDueDate',
        'status' => 'getStatus',
        'description' => 'getDescription',
        'project' => 'getProject',
        'ticketType' => 'getTicketType',
        'account' => 'getAccount',
        'contact' => 'getContact',
        'parentTicket' => 'getParentTicket',
        'attachments' => 'getAttachments',
        'tags' => 'getTags',
        'remoteCreatedAt' => 'getRemoteCreatedAt',
        'remoteUpdatedAt' => 'getRemoteUpdatedAt',
        'remoteData' => 'getRemoteData',
        'remoteWasDeleted' => 'getRemoteWasDeleted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['remoteId'] = $data['remoteId'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['assignees'] = $data['assignees'] ?? null;
        $this->container['dueDate'] = $data['dueDate'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['project'] = $data['project'] ?? null;
        $this->container['ticketType'] = $data['ticketType'] ?? null;
        $this->container['account'] = $data['account'] ?? null;
        $this->container['contact'] = $data['contact'] ?? null;
        $this->container['parentTicket'] = $data['parentTicket'] ?? null;
        $this->container['attachments'] = $data['attachments'] ?? null;
        $this->container['tags'] = $data['tags'] ?? null;
        $this->container['remoteCreatedAt'] = $data['remoteCreatedAt'] ?? null;
        $this->container['remoteUpdatedAt'] = $data['remoteUpdatedAt'] ?? null;
        $this->container['remoteData'] = $data['remoteData'] ?? null;
        $this->container['remoteWasDeleted'] = $data['remoteWasDeleted'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets remoteId
     *
     * @return string|null
     */
    public function getRemoteId()
    {
        return $this->container['remoteId'];
    }

    /**
     * Sets remoteId
     *
     * @param string|null $remoteId The third-party API ID of the matching object.
     *
     * @return self
     */
    public function setRemoteId($remoteId)
    {
        $this->container['remoteId'] = $remoteId;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The ticket's name.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets assignees
     *
     * @return string[]|null
     */
    public function getAssignees()
    {
        return $this->container['assignees'];
    }

    /**
     * Sets assignees
     *
     * @param string[]|null $assignees assignees
     *
     * @return self
     */
    public function setAssignees($assignees)
    {
        $this->container['assignees'] = $assignees;

        return $this;
    }

    /**
     * Gets dueDate
     *
     * @return \DateTime|null
     */
    public function getDueDate()
    {
        return $this->container['dueDate'];
    }

    /**
     * Sets dueDate
     *
     * @param \DateTime|null $dueDate The ticket's due date.
     *
     * @return self
     */
    public function setDueDate($dueDate)
    {
        $this->container['dueDate'] = $dueDate;

        return $this;
    }

    /**
     * Gets status
     *
     * @return TicketStatusEnum|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param TicketStatusEnum|null $status The current status of the ticket.
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The ticket's description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets project
     *
     * @return string|null
     */
    public function getProject()
    {
        return $this->container['project'];
    }

    /**
     * Sets project
     *
     * @param string|null $project project
     *
     * @return self
     */
    public function setProject($project)
    {
        $this->container['project'] = $project;

        return $this;
    }

    /**
     * Gets ticketType
     *
     * @return string|null
     */
    public function getTicketType()
    {
        return $this->container['ticketType'];
    }

    /**
     * Sets ticketType
     *
     * @param string|null $ticketType The ticket's type.
     *
     * @return self
     */
    public function setTicketType($ticketType)
    {
        $this->container['ticketType'] = $ticketType;

        return $this;
    }

    /**
     * Gets account
     *
     * @return string|null
     */
    public function getAccount()
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param string|null $account account
     *
     * @return self
     */
    public function setAccount($account)
    {
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return string|null
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param string|null $contact contact
     *
     * @return self
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets parentTicket
     *
     * @return string|null
     */
    public function getParentTicket()
    {
        return $this->container['parentTicket'];
    }

    /**
     * Sets parentTicket
     *
     * @param string|null $parentTicket parentTicket
     *
     * @return self
     */
    public function setParentTicket($parentTicket)
    {
        $this->container['parentTicket'] = $parentTicket;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return string[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param string[]|null $attachments attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets remoteCreatedAt
     *
     * @return \DateTime|null
     */
    public function getRemoteCreatedAt()
    {
        return $this->container['remoteCreatedAt'];
    }

    /**
     * Sets remoteCreatedAt
     *
     * @param \DateTime|null $remoteCreatedAt When the third party's ticket was created.
     *
     * @return self
     */
    public function setRemoteCreatedAt($remoteCreatedAt)
    {
        $this->container['remoteCreatedAt'] = $remoteCreatedAt;

        return $this;
    }

    /**
     * Gets remoteUpdatedAt
     *
     * @return \DateTime|null
     */
    public function getRemoteUpdatedAt()
    {
        return $this->container['remoteUpdatedAt'];
    }

    /**
     * Sets remoteUpdatedAt
     *
     * @param \DateTime|null $remoteUpdatedAt When the third party's ticket was updated.
     *
     * @return self
     */
    public function setRemoteUpdatedAt($remoteUpdatedAt)
    {
        $this->container['remoteUpdatedAt'] = $remoteUpdatedAt;

        return $this;
    }

    /**
     * Gets remoteData
     *
     * @return \OpenAPI\Client\Model\RemoteData[]|null
     */
    public function getRemoteData()
    {
        return $this->container['remoteData'];
    }

    /**
     * Sets remoteData
     *
     * @param \OpenAPI\Client\Model\RemoteData[]|null $remoteData remoteData
     *
     * @return self
     */
    public function setRemoteData($remoteData)
    {
        $this->container['remoteData'] = $remoteData;

        return $this;
    }

    /**
     * Gets remoteWasDeleted
     *
     * @return bool|null
     */
    public function getRemoteWasDeleted()
    {
        return $this->container['remoteWasDeleted'];
    }

    /**
     * Sets remoteWasDeleted
     *
     * @param bool|null $remoteWasDeleted remoteWasDeleted
     *
     * @return self
     */
    public function setRemoteWasDeleted($remoteWasDeleted)
    {
        $this->container['remoteWasDeleted'] = $remoteWasDeleted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


